### ISSUE TITLE
breeding phase assumptions

### ISSUE THREAD

**Issue by samdavey** [samdavey/penguins#16]
@ErinClitheroe : Can you confirm these assumptions for me regarding the breeding phases?

If an egg is laid, but never hatches, we assume that the 35 days after laying is the 'incubation period'.

If an egg hatches, but there is no fledge record, we assume that the 80 days following hatching are the 'rearing' period, unless another clutch is laid before that. In most cases we either have a Fledge record or a Dead record, so this is to pick up the hatched-but-missing chicks.

**Comment by ErinClitheroe** [comment]
Hi Sam

to answer.
1. If an egg is laid, but never hatches, we assume that the 35 days after laying is the 'incubation period'. 

Yes. after this stage the unhatched egg is no longer being incubated
1. If an egg hatches, but there is no fledge record, we assume that the 80 days following hatching are the 'rearing' period, unless another clutch is laid before that. In most cases we either have a Fledge record or a Dead record, so this is to pick up the hatched-but-missing chicks.

i have actually gone through and populated the breeding table following my fledge vs dead rules so there should now be no missing chicks without a final corresponding dead or fledged record. does this make sense? however if i have missed any then i would define the rearing period as 60 days follwing hatching, unless another clutch is laid before that. :) 

I am wondering how we get the "chicks hatched" record? is that from the total number fledged and total number dead? :)

**Comment by samdavey** [comment]
Re question 2: I'm defining hatch_date as follows
Hatch_date = (observation_date for first instance of chicks_alive or chicks_dead) - chick-age
Does that sound reasonable? I assume that you've guessed the age of the chick based on their size / weight or something at the first observation, but you've done this a lot so it's probably pretty accurate.

**Comment by ErinClitheroe** [comment]
Yep sounds spot on. I'm confident my age estimates are accurate within 2-3 days
