### ISSUE TITLE
Get weather pressure from BOM

### ISSUE THREAD

**Issue by samdavey** [samdavey/penguins#7]
Useful for RH calcs

**Comment by ErinClitheroe** [comment]
what intervals? half-hourly, hourly daily?

**Comment by samdavey** [comment]
Let's park this one for the time being and reopen it if we think there are valid hypotheses related to it. At the moment I don't think it will add much.

**Comment by ErinClitheroe** [comment]
no problem :) i am just waiting on data from BOM with half hourly measurements of ambient temperature, relative humidity and wind speed and direction. they said i should have it within 5 days. i also have daily max temp, daily min temp, and daily rainfall. i will send through these data
